.gitignore, client/components/navbar.js, client/components/resident/news-board.js, client/components/resident/news-new.js, client/components/resident/news-post-item.js, client/components/resident/news.js, client/components/resident/profile-form.js, client/components/resident/profile.js, client/components/resident/ticket-current.js, client/components/resident/ticket-form.js, client/components/resident/ticket-history.js, client/components/resident/ticket-item.js, client/components/resident/utils.js, package-lock.json, package.json, public/index.html, server/db/index.js, server/db/models/apartment.js, server/db/models/building.js, server/db/models/index.js, server/db/models/news.js, server/db/models/owner.js, server/db/models/resident.js, server/db/models/ticket.js, server/db/models/user.js, server/db/models/worker.js, server/index.js
=> Model update

script/seed.js, server/api/index.js, server/api/owner.js, server/api/resident.js, server/api/users.js, server/db/models/news.js, server/db/models/ticket.js
Please add a description of this Pull Request's motivation, scope, outstanding issues or potential alternatives, reasoning behind the current solution, and any other relevant information for posterity.
---
_Your PR Notes Here_
Manny is a bad guy
=> Routes update

server/api/owner.js, server/api/resident.js, server/api/tests/owner.spec.js, server/api/tests/resident.spec.js
tests are not completely passing.
some logic in the routes is faulty and needs to be reworked.
I tried to make them as comprehensive as possible. They should probably be split into different files because of line length but can always do that later
=> Test update

client/store/user.js
temp fix to allow pair programming to work
=> fix: update redux store to know perms for user temp

client/components/navbar.js, client/components/owner/all-buildings.js, client/components/owner/building-form.js, client/components/owner/single-building.js, client/components/owner/tickets.js, client/routes.js, client/store/index.js, client/store/owner.js, client/store/user.js, script/seed.js, server/api/owner.js
Can 
- view all buildings for an owner #21 
- view single building #23 
- view tickets for that building #10 
- add new building (just address) 
- owners logged in will see buildings tab #7
=> first draft for owner update

client/components/navbar.js, client/store/user.js, server/auth/index.js, server/db/models/user.js
/auth/login and /auth/me now return isOwner and isResident flags bools to allow front end to correctly display things
=> feat: auth pages now send permissions

client/components/resident/ticket-form.js, client/components/resident/ticket-item.js, client/components/resident/ticket-new.js, client/components/resident/tickets.js, client/components/user-home.js, client/routes.js, client/store/resident.js, script/seed.js, server/api/resident.js
The resident is able to create and submit a new ticket in /tickets
=> Resident ticket

client/components/resident/news-new.js, client/components/resident/news-post.js, client/components/resident/news.js, client/components/user-home.js, client/routes.js, client/store/resident.js, server/api/resident.js, server/api/tests/resident.spec.js, server/db/models/ticket.js
resident could add new post
resident sees a list of all news in the building
=> Resident news

client/components/navbar.js, client/components/user-home.js, client/components/worker/all-tickets.js, client/components/worker/new-worker.js, client/routes.js, client/store/index.js, client/store/worker.js, public/style.css, server/api/owner.js, server/api/worker.js, server/db/models/user.js, server/db/models/worker.js
- New users can register as workers: resolves #38 
- Workers can log in: resolves #40 
- Workers can see assigned and in-progress tickets (in terms of status): resolves #37
=> Feature: User can sign up as worker, workers can log in

client/components/worker/new-worker.js, server/api/worker.js
read commits
There is no serverside verification of the skills.
This could be considered a security vulnerability but it's probably ok.
As long as we add verification for workers eventually, we'll be good
resolves #50
=> Worker skills

client/components/worker/all-tickets.js, client/store/worker.js, server/api/worker.js
- Worker can update ticket status from assigned to in-progress
- Worker can update ticket status from in-progress to finished
Resolves #36
=> Feature: worker can update status of ticket to in-progress or finished

client/components/owner/news.js, client/components/resident/news-new.js, client/components/resident/news.js, client/routes.js
resolves #43 
Can view news for a single building
Fixed bug where resident can post empty news by accident.
Should fix it with validators though
=> Owner news view

client/components/owner/tickets.js, client/store/owner.js, server/api/owner.js, server/api/tests/owner.spec.js, server/db/models/ticket.js
- Ticket model status now consists of [pending, approved, rejected, in-progress, finished, confirmed, closed]
- Owner can either approve or reject a pending ticket: resolves #60 
- Deleted two tests from Owner tests that checked if owner can assign a worker
=> Feat: Owner can update status of ticket from pending to approved or rejected

script/seed.js
rewrote the seed file to use actual ids and not make them on the fly.
The previous version was not updated the seq. correctly and was causing unique constraint errors
=> feat: seed file does not use hardcoded ids anymore

client/components/worker/all-tickets.js, client/components/worker/current-tickets.js, client/store/worker.js, server/api/worker.js
Resolves #59 
- Worker can select a ticket
- Upon selection the ticket's status changes from approved to in-progress and assigns workerId
- Worker can change status of in-progress ticket to finished
=> Worker update status

client/components/owner/news.js, client/store/owner.js, server/api/owner.js, server/api/resident.js, server/api/tests/owner.spec.js
closes #44 
owners can now approve or reject news posts
tests have been updated
=> Owner news update

client/components/user-home.js, client/components/user-home.spec.js, client/store/resident.js, server/api/resident.js
=> Resident homepage - display building address and apartment number

client/components/owner/news-new.js, client/components/owner/single-building.js, client/components/owner/single-resident.js, client/components/owner/verified-residents.js, client/routes.js, client/store/owner.js, server/api/owner.js
Resolves #68 
- Single building view only displays link to verified residents of that building
- Link leads to list of all verified residents (names are links)
- Link of verified resident name leads to resident's profile page
=> Resident profile view for Owner

client/app.js, client/components/css/app.scss
basic skeleton for using scss in this project
import where needed or make smaller files if needed
=> feat: skeleton for scss moving forward

public/style.css
=> Style update

client/components/navbar.js, client/components/owner/workers.js, package-lock.json
Just made buttons for approving and rejecting unverified workers on owner view: handles #95
=> style: change old button to new flashy buttons

client/components/navbar.js, client/components/owner/all-residents.js, client/components/owner/all-users.js, client/components/owner/workers.js, client/components/us/home-main.js, client/routes.js, server/api/owner.js
- All links should work for owner: resolves #97 
- Links on main home should for work guest user (get started => links to "/signup")
=> Make links work for owner and on main-home

client/components/css/owner/ticket.scss, client/components/navbar.js, client/components/owner/single-ticket.js, client/components/owner/tickets.js, client/routes.js, client/store/owner.js, package-lock.json, package.json, server/api/owner.js
visual updates and keeping the same features
Added cool moment js library for time stuff
Image is not displayed yet tho
=> Owner ticket update

client/components/navbar.js, client/components/resident/new-resident-draft.js, client/components/resident/new-resident.js, client/components/worker/new-worker.js
update navbar for users that are logged in but are not resident/worker/owner
=> Navbar update

client/components/worker/ticket-completed.js, client/components/worker/ticket-current.js, client/components/worker/ticket-new.js, client/routes.js, client/store/worker.js, server/api/worker.js
- Completed Tickets renders
- Buttons work
=> fix: correct routes and links and components to render for each link

client/components/owner/single-building.js, client/components/owner/single-resident.js, client/components/owner/unverified-resident.js, client/components/owner/verified-resident.js, client/routes.js
=> style: update

client/components/owner/all-residents.js, client/components/owner/all-users.js, client/components/owner/building-form.js, client/components/owner/single-building-residents.js, client/components/owner/single-building-vacancy.js, client/components/owner/ticket-list.js, client/components/owner/workers.js, client/components/us/home-main.js, client/components/us/pricing.js, public/style.css
Owner's View Style Updates:
-all users
-add new property
-change main home page mockup photo
-pricing page
=> Style updates

script/seed.js
=> fix: seed update
